apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: backend

images:
  - name: ghcr.io/davidrgodwin/multiplayer-quiz-backend
    newTag: latest  # CD pipeline updates this to the git SHA on every merge to main
